### ISSUE TITLE
配置中心map属性删除某个key时，业务系统中实际并没有被删除

### ISSUE THREAD

**Issue by akaks** [nacos-group/nacos-spring-boot-project#100]
配置中心支持了配置listmap 属性（configuration），yaml文件如下
listMap:
l1: "New York Mets"
l2: "Chicago Cubs"

当更新配置中心，将l2删除时，实际l2并不会被删除，而是会保留下来
#######################################################
The configuration center supports configuration listmap properties (configuration), and the yaml file is shown below
ListMap:
L1: "the New York Mets." "
L2: "Chicago Cubs." "
When the configuration is updated to remove l2, the actual l2 is not removed, but retained
#######################################################

Issue Description
Type: bug report

Describe what happened (or what feature you want)
Describe what you expected to happen
How to reproduce it (as minimally and precisely as possible)
Tell us your environment
Anything else we need to know?

**Comment by akaks** [comment]
![image](https://user-images.githubusercontent.com/22937815/71438106-59195500-272f-11ea-82db-16f39c534e12.png)


目前我使用ObjectUtils.cleanMapOrCollectionField(bean);将bean清空，可以避免map的key删不掉的清空

**Comment by chuntaojun** [comment]
version 报一下

**Comment by chuntaojun** [comment]
确实是一个bug，已修复好了
