### ISSUE TITLE
springboot yaml格式启动报错（${demo.useLocalCache}）

### ISSUE THREAD

**Issue by lawbc** [nacos-group/nacos-spring-boot-project#108]
@NacosValue(value = "${demo.useLocalCache}", autoRefreshed = true)

上面这种配置就报错，如果没有层级（demo没有）就可以

**Comment by chuntaojun** [comment]
是否显示声明了相关配置的文件格式，或者在data-id中携带有配置文件的格式信息？如果没有可能会被错误的格式化导致上述问题

**Comment by lawbc** [comment]
感谢您的回复！
代码里面没有看到是可以配置文件格式的，只有在nacos控制台可以选择不同的格式，我是直接在nacos-spring-boot-example项目里面直接修改NacosValue注解的，用useLocalCache（没有层级并且控制台设置properties类型）那么就可以，如果改成demo.useLocalCache，控制台改成yaml就是启动报错，错误提示如下：
Injection of @com.alibaba.nacos.api.config.annotation.NacosValue dependencies is failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'demo.useLocalCache' in value "${demo.useLocalCache}"

**Comment by chuntaojun** [comment]
@NacosValue是其中一个注解，你肯定还有某个地方需要加载远程配置的设置

**Comment by lawbc** [comment]
这里有个跟我一样的问题：http://www.mamicode.com/info-detail-2662205.html

**Comment by chuntaojun** [comment]
贴一下你的相关配置，这样无法确定问题

发自我的iPhone

在 2020年3月3日，10:30，lawbc <notifications@github.com> 写道：

﻿

这里有个跟我一样的问题：http://www.mamicode.com/info-detail-2662205.html
