### ISSUE TITLE
nacos-discovery-spring-boot-starter 中命名空间配置失效

### ISSUE THREAD

**Issue by jonerxq** [nacos-group/nacos-spring-boot-project#11]
nacos:
  config:
    server-addr: 127.0.0.1:8848
    namespace: 67cea0fe-daef-48fe-a9c6-488aee2f4f74
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: 67cea0fe-daef-48fe-a9c6-488aee2f4f74
发现 注册后是 Public 的命名空间
![image](https://user-images.githubusercontent.com/4024931/52842806-31368980-313b-11e9-90e6-8e90105e954a.png)

查看源码发现与api 的 说明不符合
public void registerService(String serviceName, Instance instance) throws NacosException {

        LogUtils.LOG.info("REGISTER-SERVICE", "registering service " + serviceName + " with instance:" + instance);

        final Map<String, String> params = new HashMap<String, String>(8);
        params.put("tenant", namespace);   要替换成namespaceId
        params.put("ip", instance.getIp());
        params.put("port", String.valueOf(instance.getPort()));
        params.put("weight", String.valueOf(instance.getWeight()));
        params.put("healthy", String.valueOf(instance.isHealthy()));
        params.put("metadata", JSON.toJSONString(instance.getMetadata()));
        if (instance.getService() == null) {
            params.put("serviceName", serviceName);
        } else {
            params.put("service", JSON.toJSONString(instance.getService()));
        }
        params.put("cluster", JSON.toJSONString(instance.getCluster()));

        reqAPI(UtilAndComs.NACOS_URL_INSTANCE, params, "PUT");
    }

**Comment by fangjian0423** [comment]
Naming service support namespace is support in [nacos 0.8.0](https://github.com/alibaba/nacos/releases/tag/0.8.0).

We will upgrade nacos-spring version to support it.

**Comment by chuntaojun** [comment]
already fix，Wait for me to raise pr

**Comment by chuntaojun** [comment]
#31
