### ISSUE TITLE
请问什么时候能够支持nacos1.2.0版本

### ISSUE THREAD

**Issue by waters321** [nacos-group/nacos-spring-boot-project#110]
请问什么时候能够支持nacos1.2.0版本

**Comment by chuntaojun** [comment]
will be come soon

发自我的iPhone

在 2020年3月5日，18:07，张淼 <notifications@github.com> 写道：

﻿

请问什么时候能够支持nacos1.2.0版本

**Comment by waters321** [comment]
请问这个是不是还没有发布到中央仓库?
