### ISSUE TITLE
springboot 同个环境多配置文件部署如何使用@NacosConfigListener

### ISSUE THREAD

**Issue by chenjianshuo** [nacos-group/nacos-spring-boot-project#115]
例如一个项目在同个pord环境中要部署prod1,prod2,prod3,3份配置文件，在3份配置文件中分别定于
### application-pord1.properties:
nacos.config.server-addr=172.25.32.238:8848
nacos.config.namespace=1076a42b-0b04-43ad-8ffd-d4937ddac74b
nacos.dataId=prod1.yml

### application-pord1.properties:
nacos.dataId=prod2.yml
nacos.config.server-addr=172.25.32.238:8848
nacos.config.namespace=1076a42b-0b04-43ad-8ffd-d4937ddac74b

### application-pord1.properties:
nacos.config.server-addr=172.25.32.238:8848
nacos.config.namespace=1076a42b-0b04-43ad-8ffd-d4937ddac74b
nacos.dataId=prod3.yml
@NacosPropertySource(dataId = "${nacos.dataId}", autoRefreshed = true,type = ConfigType.YAML)

  @NacosConfigListener(dataId = "${nacos.dataId}",type = ConfigType.YAML) 均报错  有什么方式可
以解决这种情况吗
![image](https://user-images.githubusercontent.com/19216400/76743338-70576400-67ad-11ea-8bc1-fd65f7d56d2c.png)

---------------------
环境： <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.1.2</version>
        </dependency>

**Comment by chuntaojun** [comment]
升级你的版本到0.2.4以上

**Comment by chenjianshuo** [comment]
springboot 1.3.7适用0.2.4吗

**Comment by chuntaojun** [comment]
那你可以使用0.1.4

发自我的iPhone

在 2020年3月16日，17:58，chenjianshuo <notifications@github.com> 写道：

﻿

springboot 1.3.7适用0.2.4吗

**Comment by chenjianshuo** [comment]
![image](https://user-images.githubusercontent.com/19216400/76746402-6be17a00-67b2-11ea-90e6-b8191363eedd.png)
用了0.1.4后还是有问题

**Comment by chuntaojun** [comment]
看一下nacos-spring-context版本

发自我的iPhone

在 2020年3月16日，18:18，chenjianshuo <notifications@github.com> 写道：

﻿

[image]<https://user-images.githubusercontent.com/19216400/76746402-6be17a00-67b2-11ea-90e6-b8191363eedd.png>
用了0.1.4后还是有问题

**Comment by chenjianshuo** [comment]
没有配置nacos-spring-context
 只配置了<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>${project.version}</version>
        </dependency>

**Comment by chenjianshuo** [comment]
没有配置nacos-spring-context
只配置了    <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.1.4</version>

**Comment by chuntaojun** [comment]
我这里是ok的

![截屏2020-03-16下午7 28 05](https://user-images.githubusercontent.com/23445172/76753984-54a78a00-67bc-11ea-8d56-fc855251708c.png)

**Comment by chenjianshuo** [comment]
请问你尝试的是springboot版本1.3.7
nacos-spring：0.1.4吗
![image](https://user-images.githubusercontent.com/19216400/76817622-5c0f7780-683e-11ea-8e45-de3b8ccdd621.png)
