### ISSUE TITLE
NacosConfigListener不能只监听有变动的配置吗

### ISSUE THREAD

**Issue by chenjianshuo** [nacos-group/nacos-spring-boot-project#118]
NacosConfigListener不能只监听有变动的配置吗，这样不用监听全部，不会造成资源浪费

**Comment by chuntaojun** [comment]
> NacosConfigListener不能只监听有变动的配置吗，这样不用监听全部，不会造成资源浪费

Nacos的配置管理最小的粒度就是整个文件，而不是某个配置项

**Comment by chuntaojun** [comment]
你可以把频繁变动的和不变动的进行拆分

**Comment by chuntaojun** [comment]
> 你可以把频繁变动的和不变动的进行拆分

在最新的的nacos-client中，有一个AbstractConfigChangeListener，可以识别变动的配置项

**Comment by chenjianshuo** [comment]
需要升级到哪个版本，现在用0.2.4



---原始邮件---
发件人: "liaochuntao"<notifications@github.com&gt;
发送时间: 2020年3月19日(周四) 中午12:07
收件人: "nacos-group/nacos-spring-boot-project"<nacos-spring-boot-project@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chenjianshuo"<120457817@qq.com&gt;;
主题: Re: [nacos-group/nacos-spring-boot-project] NacosConfigListener不能只监听有变动的配置吗 (#118)




  
你可以把频繁变动的和不变动的进行拆分
  
在最新的的nacos-client中，有一个AbstractConfigChangeListener，可以识别变动的配置项
