### ISSUE TITLE
Failed to instantiate [com.alibaba.boot.nacos.actuate.endpoint.NacosConfigEndpoint]

### ISSUE THREAD

**Issue by salovexb** [nacos-group/nacos-spring-boot-project#12]
spring boot version: 1.5.15.RELEASE
nacos-config-spring-boot-starter、nacos-discovery-spring-boot-starter version：0.1.1
nacos-config-spring-boot-actuator、nacos-discovery-spring-boot-actuator version: 0.1.1
application.yml配置
nacos: 
  config: 
    enabled: true
    server-addr: 127.0.0.1:8848
  discovery: 
    enabled: true
    server-addr: 127.0.0.1:8848

工程启动报错信息：Failed to instantiate [com.alibaba.boot.nacos.actuate.endpoint.NacosConfigEndpoint]: Factory method 'nacosEndpoint' threw exception; nested exception is java.lang.IllegalArgumentException: Id must only contains letters, numbers and '_'

**Comment by fangjian0423** [comment]
Different spring boot version has different endpoint parse rule. Maybe you could degrade springboot version to 1.4.x.

We will fix it in the future.
