### ISSUE TITLE
使用nacos做配置中心，data id配置为java包名时，启动时解析配置异常

### ISSUE THREAD

**Issue by chuntaojun** [nacos-group/nacos-spring-boot-project#125]
https://github.com/alibaba/nacos/issues/2658

**Comment by chuntaojun** [comment]
need to adjust the priority of reading the file format in the data-id and setting the file format with the type attribute

**Comment by twogozi** [comment]
you mean that the suffix name of the data-id is the file format and has a high priority

**Comment by chuntaojun** [comment]
> you mean that the suffix name of the data-id is the file format and has a high priority

Yes, so some adjustments need to be made
