### ISSUE TITLE
Is it possible to put the dubbo configuration into the configuration center?

### ISSUE THREAD

**Issue by liunancun** [nacos-group/nacos-spring-boot-project#14]
Is it possible to put the dubbo configuration into the configuration center?

dubbo.application.name=bessky-boot-service
dubbo.protocol.name=dubbo
dubbo.protocol.port=28000
dubbo.scan.basePackages=com.bessky
dubbo.registry.address=zookeeper://192.168.99.230:2181

**Comment by chuntaojun** [comment]
In the new version has achieved, currency can be used from the compilation of source code under the watch, and see the instructions on the use of the wiki
