### ISSUE TITLE
SpringBoot 2.2.7 + dubbo 2.7.6 + Nacos 0.2.7配置可以加载但是不能刷新

### ISSUE THREAD

**Issue by yeyue2019** [nacos-group/nacos-spring-boot-project#142]
**配置文件**
![image](https://user-images.githubusercontent.com/55351840/88788197-93683a80-d1c7-11ea-8006-17974a1a2145.png)

**配置内容**
![image](https://user-images.githubusercontent.com/55351840/88788261-aa0e9180-d1c7-11ea-831c-dd3e66ce135c.png)

**调用方法**
![image](https://user-images.githubusercontent.com/55351840/88789508-62890500-d1c9-11ea-9664-e9fc1bb73a57.png)

**监听到变化**
![image](https://user-images.githubusercontent.com/55351840/88789574-7b91b600-d1c9-11ea-9d93-7bdedfb4f334.png)

**但是修改配置后不能自动刷新，这是bug吗还是兼容有问题**

**Comment by yeyue2019** [comment]
配置能拉到，但是修改配置后配置不能刷新

**Comment by yeyue2019** [comment]
需要同步引入关于spring的依赖

**Comment by Yuqn** [comment]
请问需要加上什么依赖，我看代码，描述的是环境中已经是新的配置了，实际上还是旧的配置
