### ISSUE TITLE
@NacosPropertySource 只支持properties格式文件，希望可以多种格式的配置文件，例如yaml,或者提供像@PropertySourced的实现，支持factory扩展加载自定义格式配置文件

### ISSUE THREAD

**Issue by bedlimate** [nacos-group/nacos-spring-boot-project#17]

**Comment by fangjian0423** [comment]
It is a feature of https://github.com/nacos-group/nacos-spring-project and we will do it soon.

**Comment by chuntaojun** [comment]
I will try to make it

**Comment by chuntaojun** [comment]
#31 , you can see here [nacos-spring-project wiki](https://github.com/nacos-group/nacos-spring-project/wiki/Nacos-Spring-Project-0.3.1-%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C)

**Comment by Razor0719** [comment]
@chuntaojun 
is nacos springboot 0.2.1 & 0.1.1 support yaml or other type?or it is not released?
I try to use yaml but only properties be effective

**Comment by chuntaojun** [comment]
> @chuntaojun
> is nacos springboot 0.2.1 & 0.1.1 support yaml or other type?or it is not released?
> I try to use yaml but only properties be effective
> 
> oh,and i find version 0.3.0 can support it
> which spring boot version can use it?

maybe you just can make source code to build jar use it,
