### ISSUE TITLE
@ConditionalOnProperty 配置不生效

### ISSUE THREAD

**Issue by icc99** [nacos-group/nacos-spring-boot-project#18]
@ConditionalOnProperty(value = "dispatch.consumer.enabled", havingValue = "true", matchIfMissing = true)

配置如下
dispatch.consumer.enabled=false

如果配置在application.properties文件里面就生效

放在nacos就不生效

**Comment by fangjian0423** [comment]
Hi.

@ConditionalOnProperty will be handled in the refresh process of `ApplicationContext`.  

Nacos has not been initialized at that time. 

So it don't take effect.

**Comment by liunancun** [comment]
@fangjian0423 阿波罗好像可以支持@ConditionalOnProperty，请问nacos后面会支持吗？

**Comment by chuntaojun** [comment]
> @fangjian0423 阿波罗好像可以支持@ConditionalOnProperty，请问nacos后面会支持吗？

正在尝试支持此注解

**Comment by chuntaojun** [comment]
> @fangjian0423 阿波罗好像可以支持@ConditionalOnProperty，请问nacos后面会支持吗？

already support it，wait for the new release

**Comment by chenglin321** [comment]
> > @fangjian0423 阿波罗好像可以支持@ConditionalOnProperty，请问nacos后面会支持吗？
> 
> already support it，wait for the new release

您好，请问哪个版本修复了？

**Comment by chuntaojun** [comment]
从0.2.2或者0.1.2开始就修复了，可以看下wiki

发自我的iPhone

在 2020年4月19日，09:40，chenglin321 <notifications@github.com> 写道：

﻿

@fangjian0423<https://github.com/fangjian0423> 阿波罗好像可以支持@ConditionalOnProperty，请问nacos后面会支持吗？

already support it，wait for the new release

您好，请问哪个版本修复了？

**Comment by chenglin321** [comment]
@chuntaojun 
nacos-config-spring-boot-starter 0.2.2 
spring-boot-starter-parent   2.1.3.RELEASE
写了个demo测试，还是不行。
只能进入restTemplate2中的断点，把appcation.properties的redis.switch=true注释打开，两个restTemplate2和restTemplate都能进去。
![image](https://user-images.githubusercontent.com/3918176/79679193-3e1aa580-8236-11ea-9b73-5d4a21270bbc.png)

![image](https://user-images.githubusercontent.com/3918176/79679185-2fcc8980-8236-11ea-972e-4e07e9b70fd2.png)

![image](https://user-images.githubusercontent.com/3918176/79679168-0c094380-8236-11ea-9653-6305ba39feb7.png)

![image](https://user-images.githubusercontent.com/3918176/79679155-f136cf00-8235-11ea-8e36-77bfcb597d15.png)

**Comment by chuntaojun** [comment]
参考项目的wiki以及example

发自我的iPhone

在 2020年4月19日，12:10，chenglin321 <notifications@github.com> 写道：

﻿

@chuntaojun<https://github.com/chuntaojun>
nacos-config-spring-boot-starter 0.2.2
spring-boot-starter-parent 2.1.3.RELEASE
写了个demo测试，还是不行。
只能进入restTemplate2中的断点，把appcation.properties的redis.switch=true注释打开，两个restTemplate2和restTemplate都能进去。
[image]<https://user-images.githubusercontent.com/3918176/79679193-3e1aa580-8236-11ea-9b73-5d4a21270bbc.png>

[image]<https://user-images.githubusercontent.com/3918176/79679185-2fcc8980-8236-11ea-972e-4e07e9b70fd2.png>

[image]<https://user-images.githubusercontent.com/3918176/79679168-0c094380-8236-11ea-9653-6305ba39feb7.png>

[image]<https://user-images.githubusercontent.com/3918176/79679155-f136cf00-8235-11ea-8e36-77bfcb597d15.png>

**Comment by chenglin321** [comment]
@chuntaojun可以了。谢谢。

**Comment by zhangqlbc136** [comment]
@chenglin321 怎么解决的，我把版本都升级了还是不支持呢

**Comment by chenglin321** [comment]
@zhangqlbc136 看下wiki，yml配置有改动。
nacos.config.data-ids=people,test
nacos.config.type=properties
nacos.config.auto-refresh=true

**Comment by liangxianjin** [comment]
> @chuntaojun可以了。谢谢。

嗨，哥们。你这个问题怎么处理好的，我这spring-boot中大量用到了
@ConditionalOnProperty 配置不生效

**Comment by chenglin321** [comment]
> ![image](https://user-images.githubusercontent.com/45254883/125440333-ef46db9d-db7e-445a-b6df-e0fd3e92dce3.png)
> 
> 我这看了wiki文档官方demo集成到项目中还是不对，哎

兄弟，搞好没？
我用的是：
nacos-config-spring-boot-starter 0.2.2
spring-boot-starter-parent 2.1.3.RELEASE
nacos1.4.1

把Application启动类的dataid，修改到springboot的application.properties

nacos.config.data-ids=你的dataId
nacos.config.type=properties
nacos.config.auto-refresh=true

**Comment by chenglin321** [comment]
@liangxianjin 
兄弟，搞好没？
我用的是：
nacos-config-spring-boot-starter 0.2.2
spring-boot-starter-parent 2.1.3.RELEASE
nacos1.4.1

把Application启动类的dataid，修改到springboot的application.properties

nacos.config.data-ids=你的dataId
nacos.config.type=properties
nacos.config.auto-refresh=true

**Comment by liangxianjin** [comment]
之前看的也是jar问题，可以了，后来切换项目，开发别的应用；这块又还原为原来的代码，又不好使了，确定是jar包问题，应该不难

**Comment by liangxianjin** [comment]
> @liangxianjin
> 兄弟，搞好没？
> 我用的是：
> nacos-config-spring-boot-starter 0.2.2
> spring-boot-starter-parent 2.1.3.RELEASE
> nacos1.4.1
> 
> 把Application启动类的dataid，修改到springboot的application.properties
> 
> nacos.config.data-ids=你的dataId
> nacos.config.type=properties
> nacos.config.auto-refresh=true

之前看的也是jar问题，可以了，后来切换项目，开发别的应用；这块又还原为原来的代码，又不好使了，确定是jar包问题，应该不难
