### ISSUE TITLE
这个项目烂尾了吗

### ISSUE THREAD

**Issue by duansheli** [nacos-group/nacos-spring-boot-project#214]
2021都块过去了
还有那么些提交没人管
![image](https://user-images.githubusercontent.com/8579595/142726708-43fe9d5f-4d90-4568-af10-09aac8b231b6.png)

**Comment by duansheli** [comment]
@realJackSun 
要是觉着提交的有问题 
也可以拒掉吧

**Comment by duansheli** [comment]
@chuntaojun

**Comment by zhouwenqi** [comment]
确实有点不懂，就连apache的dubbo都在同步支持最新版的nacos（包括springboot版的），反而自己的springboot支持还是1.3版，，有点不可思议。

**Comment by kuafoo** [comment]
阿里的项目不都这样吗

**Comment by Jalr4ever** [comment]
= = 烂尾了可还行，2022 年 2 月了，还在用 2.0.3 版本的 spring boot，现在都来到 2.6.3 了。。。

**Comment by hujun-w-2** [comment]
没有烂尾

**Comment by luyanfeng** [comment]
2023 年 4 月   springboot 3 了， jdk21了快， jdk17啥时候支持
