### ISSUE TITLE
配置中心map属性删除某个key时，业务系统中实际并没有被删除

### ISSUE THREAD

**Issue by xiaohei88** [nacos-group/nacos-spring-boot-project#215]
https://github.com/nacos-group/nacos-spring-boot-project/issues/100
说是修复了，为什么用master分支测试还是不行。

哪个版本修复的。里面也没pr

**Comment by li-xiao-shuang** [comment]
> #100 说是修复了，为什么用master分支测试还是不行。
> 
> 哪个版本修复的。里面也没pr

能否提供一下你的版本 以及复现步骤？

**Comment by xiaohei88** [comment]
nacos-spring-boot版本：0.2.10。 
nacos-server版本：2.0.3 
使用nacos-config-sample工程，在Apple里面新建了一个属性，简写如：
```java
@NacosConfigurationProperties(prefix = "apple", dataId = "test", type = ConfigType.PROPERTIES, autoRefreshed = true)
@Configuration
public class Apple {

	private Map<String, Object> map;
}
```
nacos服务端设置属性：
```properties
apple.map.b0=1
apple.map.b1=2
apple.map.b2=3
```
一开始读取出来是三个，但是我删掉两个后，读取出来的还是三个。
我看你们在`NacosConfigurationPropertiesBinder`bind时添加了ObjectUtils.cleanMapOrCollectionField(bean);
但是在`NacosBootConfigurationPropertiesBinder`没有的。因为继承了重写了doBind

**Comment by hujun-w-2** [comment]
@i will solve it@
