### ISSUE TITLE
spring-cloud-nacos和spring-boot-nacos为何不整合成一个

### ISSUE THREAD

**Issue by whbah** [nacos-group/nacos-spring-boot-project#244]
spring-cloud-nacos支持@Value，不支持@NacosValue；配置方式相对spring-boot-nacos繁琐；并且已经四个月没看到更新记录了。
spring-boot-nacos 0.2.11-Beta至少还保留了点升级的希望，但不支持@Value的自动刷新，需要对原有代码进行注解的变更。

**Comment by js20166098** [comment]
建议直接切换 springcloudnacos 配置类读取也存在类似的问题，这个组件整合的好多地方是在原基础上加一个Nacos的注解实现的

**Comment by whbah** [comment]
> 建议直接切换 springcloudnacos 配置类读取也存在类似的问题，这个组件整合的好多地方是在原基础上加一个Nacos的注解实现的

cloudnacos已经几百年没更新了，社区一潭死水。
cloud和boot的初始化参考了nacos-client的代码，但是又各自实现了部分开发者自己的想法。
一个功能的三个场景【spring boot/springcloud/springframework】实现出来的效果不一样，特别的难受

**Comment by whbah** [comment]
话说开发人员不会已经n+1了吧

**Comment by js20166098** [comment]
其实吧如果公司只用来做配置中心，可以内部自己在boot-nacos的基础上进行改写和迭代，cloudnacos虽然说社区代码已经4个月没有改动，但是好像相对来说比较稳定

**Comment by aim-pure** [comment]
有人了解springboot集成mse nacos的加密配置怎么处理吗？我这里有个问题是加密后的配置加载不到信息导致启动失败

**Comment by hujun-w-2** [comment]
试用场景都不一样，合并成一个不太合适，至于@value注解的自动刷新，看后面社区诉求高不高再决定是否做

**Comment by whbah** [comment]
> 有人了解springboot集成mse nacos的加密配置怎么处理吗？我这里有个问题是加密后的配置加载不到信息导致启动失败
spring框架要升级的，cloud只支持5.2.x

**Comment by whbah** [comment]
> 试用场景都不一样，合并成一个不太合适，至于@value注解的自动刷新，看后面社区诉求高不高再决定是否做

场景有啥不一样呢
