### ISSUE TITLE
@NacosPropertySource bug

### ISSUE THREAD

**Issue by anpu2018** [nacos-group/nacos-spring-boot-project#26]
When using @NacosPropertySource to listen to data_id in springboot application, one attribute name in multiple data_ids cannot be the same, otherwise only one will be read (tested, using multiple groups still can't solve the problem, only use different attribute names, The problem can be solved)

**Comment by chuntaojun** [comment]
@NacosPropertySource(dataId=test-1)
@NacosPropertySource(dataId=test-2)
这种设置下，如果test-1和test-2中存在两个相同的key，无法读到所有的value吗？

**Comment by anpu2018** [comment]
对

**Comment by chuntaojun** [comment]
> 对

这并不是一个bug，而是Spring的设计，environment中有一个properties链表，所有加载的配置均存在这个链表上。在进行@Value or @NacosValue 的匹配时，采取最先匹配先获取的原则

**Comment by anpu2018** [comment]
thanks
