### ISSUE TITLE
spring cloud中使用nacos， nacos无法读取application.yml中的nacos配置, 启动报错

### ISSUE THREAD

**Issue by Minam0** [nacos-group/nacos-spring-boot-project#260]
nacos-config-spring-boot-starter:0.2.11
![image](https://user-images.githubusercontent.com/22523835/182838365-7bad9aa4-4226-40d4-b407-27f72d9e4b16.png)

application.yml:
nacos:
    config:
        bootstrap:
            enable: true
        data-id: data.json
        group: DEFAULT_GROUP
        type: json
        max-retry: 10
        auto-refresh: true
        config-retry-time: 2333
        config-long-poll-timeout: 46000
        username: 
        password: 
        namespace: 
        server-addr:

**Comment by hujun-w-2** [comment]
yml截图吧，这样看不出来层级结构

**Comment by totalo** [comment]
ref #293
