### ISSUE TITLE
有计划支持spring native吗

### ISSUE THREAD

**Issue by onexuan** [nacos-group/nacos-spring-boot-project#274]
有计划支持spring native吗

**Comment by bert82503** [comment]
没人处理么

**Comment by onexuan** [comment]
> 没人处理么

自己处理吧，要把两个工程升级，nacos-spring-project 和 nacos-spring-boot-project，还要加一些类处理类被删除问题

**Comment by hujun-w-2** [comment]
已经列入开源之夏计划

**Comment by onexuan** [comment]
@hujun-w-2 速度，可以测测

**Comment by hujun-w-2** [comment]
可以看看端口是否能telnet通，服务端应该是暴露两个端口，8848 9848





------------------ 原始邮件 ------------------
发件人: fonter.yang ***@***.***&gt;
发送时间: 2023年6月4日 16:23
收件人: nacos-group/nacos-spring-boot-project ***@***.***&gt;
抄送: 胡俊 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [nacos-group/nacos-spring-boot-project] 有计划支持spring native吗 (Issue #274)





 
@hujun-w-2 速度，可以测测
