### ISSUE TITLE
springboot中application.yml配置域名读取不到配置

### ISSUE THREAD

**Issue by lgy2one** [nacos-group/nacos-spring-boot-project#277]
将nacos.config.server-addr配置成域名之后获取不到配置，一样的配置，改成ip+端口就可以，同时测试了直接curl GET 域名可以获取到配置，到底是什么问题？怎么解决？

**Comment by hujun-w-2** [comment]
配置的时候用域名:80试试

**Comment by hujun-w-2** [comment]
跟 nacos 的sdk 获取grpc端口的逻辑有关，参考：
`private ServerInfo resolveServerInfo(String serverAddress) {
        Matcher matcher = EXCLUDE_PROTOCOL_PATTERN.matcher(serverAddress);
        if (matcher.find()) {
            serverAddress = matcher.group(1);
        }
        
        String[] ipPortTuple = serverAddress.split(Constants.COLON, 2);
        int defaultPort = Integer.parseInt(System.getProperty("nacos.server.port", "8848"));
        String serverPort = CollectionUtils.getOrDefault(ipPortTuple, 1, Integer.toString(defaultPort));
        
        return new ServerInfo(ipPortTuple[0], NumberUtils.toInt(serverPort, defaultPort));
    }`
