### ISSUE TITLE
Whether to support the startup phase injection configuration, such as the scenario using @ConditionalOnProperty or some configuration that spring-boot-starter needs to read during the startup phase.

### ISSUE THREAD

**Issue by joewee** [nacos-group/nacos-spring-boot-project#28]
Whether to support the startup phase injection configuration, such as the scenario using @ConditionalOnProperty or some configuration that spring-boot-starter needs to read during the startup phase.

**Comment by chuntaojun** [comment]
I already realize this，just wait nacos-spring-context support then I‘ll pull new request to support

**Comment by joewee** [comment]
@chuntaojun Thanks for your reply

**Comment by chuntaojun** [comment]
#18
