### ISSUE TITLE
The remote-first property does not work.

### ISSUE THREAD

**Issue by qyqcswill** [nacos-group/nacos-spring-boot-project#280]
The `nacos.config.remote-first=true` property worked for some applications but not for others. Due to the spring-cloud context, I had to add the `nacos.config.bootstrap.log-enable=true` property to make it work. However, I need help finding documentation describing how the `log-enable` property works to confirm that `nacos.config.bootstrap.enable=true` is the correct property.

**Comment by qyqcswill** [comment]
pr: #282

**Comment by hujun-w-2** [comment]
请提供出现问题的spring-cloud的版本

**Comment by hujun-w-2** [comment]
see https://github.com/nacos-group/nacos-spring-boot-project/pull/293
