### ISSUE TITLE
nacos-discovery-spring-boot-starter 配置问题

### ISSUE THREAD

**Issue by slatonwu** [nacos-group/nacos-spring-boot-project#284]
1、nacos-server开启了权限认证功能
2、开启配置服务时需要配置 nacos.config.server-addr，开启自动发现时还需要配置nacos.discovery.server-addr吗？
    可不可以直接就是nacos.server-addr?
3、根据配置提示配置如下信息：
nacos.discovery.server-addr=172.22.1.48:8848,172.22.1.49:8848,172.22.1.50:8848
nacos.discovery.username=nacos
nacos.discovery.password=nacos
nacos.discovery.register.cluster-name=spring-boot
nacos.discovery.register.service-name=spring-boot
nacos.discovery.register.metadata.username=nacos
仍然报403错误，但是nacos用户确实已经添加，且可以获取到配置信息了。
Response{resultCode=500, errorCode=403, message='user not found!', requestId='null'}

能不能弄一个文档说明一下哪些配置是必填的？分别表示什么意思？

**Comment by hujun-w-2** [comment]
用户文档： https://github.com/nacos-group/nacos-spring-boot-project/wiki/%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
