### ISSUE TITLE
@NacosConfigListener Can I determine the dataId and groupId based on the environment? Now the parameter must be filled with fianl to the annotation

### ISSUE THREAD

**Issue by nkorange** [nacos-group/nacos-spring-boot-project#29]
nacos

com.alibaba.boot
nacos-config-spring-boot-starter
0.2.1
dubbo
<dubbo.version>2.7.1</dubbo.version>
spring boot
2.0.5.RELEASE

**Comment by marcus-si** [comment]
Does @NacosConfigListener support multiple different micro services to monitoring a same property file on Nacos server?

**Comment by chuntaojun** [comment]
already support read data-id from environment
