### ISSUE TITLE
请问这个项目还维护吗？到现在还不支持spring-boot 3 ~

### ISSUE THREAD

**Issue by ldcsaa** [nacos-group/nacos-spring-boot-project#297]
如题~

**Comment by zzps** [comment]
不维护了

**Comment by Daydreamer-ia** [comment]
It will support in the future. Refer to https://github.com/alibaba/nacos/issues/10375

**Comment by hujun-w-2** [comment]
已发布支持springboot3的预发布版本https://github.com/nacos-group/nacos-spring-boot-project/releases/tag/0.3.0-RC
