### ISSUE TITLE
Endpoint  nacos-discovery  service-registry 注册失败

### ISSUE THREAD

**Issue by Tank-zhu** [nacos-group/nacos-spring-boot-project#30]
public final class EndpointId {
    private static final Log logger = LogFactory.getLog(EndpointId.class);
    private static Set<String> loggedWarnings = new HashSet();
    private static final Pattern VALID_PATTERN = Pattern.compile("[a-zA-Z0-9\\.\\-]+");
    private static final Pattern WARNING_PATTERN = Pattern.compile("[\\.\\-]+");
    private final String value;
    private final String lowerCaseValue;
    private final String lowerCaseAlphaNumeric;

    private EndpointId(String value) {
        Assert.hasText(value, "Value must not be empty");
        Assert.isTrue(VALID_PATTERN.matcher(value).matches(), "Value must only contain valid chars");
        Assert.isTrue(!Character.isDigit(value.charAt(0)), "Value must not start with a number");
        Assert.isTrue(!Character.isUpperCase(value.charAt(0)), "Value must not start with an uppercase letter");
        if(WARNING_PATTERN.matcher(value).find()) {
            logWarning(value);
        }

        this.value = value;
        this.lowerCaseValue = value.toLowerCase(Locale.ENGLISH);
        this.lowerCaseAlphaNumeric = this.getAlphaNumerics(this.lowerCaseValue);
    }
//private static final Pattern WARNING_PATTERN = Pattern.compile("[\\.\\-]+"); 这里已经指定说不可以使用 - 所以会进入警告，貌似不会注册成功

**Comment by chuntaojun** [comment]
It's just warning, does not cause the program to fail
