### ISSUE TITLE
官方示例无法读取配置

### ISSUE THREAD

**Issue by yudianer** [nacos-group/nacos-spring-boot-project#308]
https://nacos.io/zh-cn/docs/quick-start-spring-boot.html 启动配置管理
本地 nacos-server版本: 2.2.3

但是使用本地nacos控制台中给的配置示例代码中client代码是可以读取配置的

**Comment by Sayi** [comment]
Hi @yudianer, you should refer to the latest examples [nacos-spring-boot-samples](https://github.com/nacos-group/nacos-spring-boot-project/tree/master/nacos-spring-boot-samples/nacos-config-sample)
