### ISSUE TITLE
nacos 集成 spring boot admin

### ISSUE THREAD

**Issue by levin950825** [nacos-group/nacos-spring-boot-project#35]
使用nacos作为服务发现无法被sba 发现

**Comment by chuntaojun** [comment]
ok，I'll try to solve it

**Comment by chuntaojun** [comment]
我这里尝试了下，发现springboot-admin是可以发现nacos-spring-boot的，你的问题方便详细描述下吗

**Comment by mosence** [comment]
我这边就是用的sba做的服务管理，可以发现的。
