### ISSUE TITLE
nacos-springboot 2.1.0

### ISSUE THREAD

**Issue by liaozan** [nacos-group/nacos-spring-boot-project#5]
`nacos-springboot`在启动时会扫描当前应用程序是否注册了`PropertySourcesPlaceholderConfigurer`,方式是通过`com.alibaba.nacos.spring.util.NacosBeanUtils#isBeanDefinitionPresent`判断是否存在，在springboot2.1.0之前的版本，启动时都会打印一句日志`Overriding user-defined bean definition for bean 'propertySourcesPlaceholderConfigurer' with a framework-generated bean definition`，debug发现，在注册PropertySourcesPlaceholderConfigurer时，spring容器beanName为`propertySourcesPlaceholderConfigurer`的beanDefinition，通过resovleBeanType解析出的beanClass为`class org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration`,并不符合所需要的beanClass(`PropertySourcesPlaceholderConfigurer`),所以nacos重复注册了一个`PropertySourcesPlaceholderConfigurer`,springboot2.1.0之前`allowBeanDefinitionOverriding`为true，但是在2.1.0中，默认为false，导致nacos启动失败，抛出异常
![image](https://user-images.githubusercontent.com/26990889/48994277-59869b80-f17d-11e8-88a3-f5c942be362b.png)
![image](https://user-images.githubusercontent.com/26990889/48994289-6c996b80-f17d-11e8-9ae5-0e96cf2d4dbe.png)

**Comment by fangjian0423** [comment]
Hi @liaozan .

You can try again using `0.2.1` version.

**Comment by liaozan** [comment]
@fangjian0423 thx
