### ISSUE TITLE
yaml文件属性类型解析

### ISSUE THREAD

**Issue by yongle** [nacos-group/nacos-spring-boot-project#56]
我们现在有个这样的字段
![image](https://user-images.githubusercontent.com/1702836/63746619-d8a92b80-c8d7-11e9-8ee7-34c193f2d2fc.png)
经过com.alibaba.nacos.spring.util.parse.DefaultYamlConfigParse#process(com.alibaba.nacos.spring.util.parse.DefaultYamlConfigParse.MatchCallback, org.yaml.snakeyaml.Yaml, java.lang.String)方法解析后，该字段被解析成了
![image](https://user-images.githubusercontent.com/1702836/63746692-03937f80-c8d8-11e9-8d42-0a74248e5cc7.png)

**Comment by chuntaojun** [comment]
You tried “000000020” set up like this

**Comment by yongle** [comment]
I tried it like this tid: '00000002', and it worked, but i think this will cause confusion in use.

**Comment by chuntaojun** [comment]
> I tried it like this tid: '00000002', and it worked, but i think this will cause confusion in use.

Parsing, but this should be yaml designers that design, automatic optimization into digital, when you are not explicitly specified as a string

**Comment by chuntaojun** [comment]
I think you directly using the application. The yaml configuration, parsing out should be the same effect

**Comment by yongle** [comment]
The SnakeYaml can use `yaml.loadAs("demo.yml", JavaBean.class);`, this will automatic optimization into `JavaBean`.

**Comment by chuntaojun** [comment]
Maybe we will not develop this function at present，If you want to configuration file to the object directly, you can use this：[NacosConfigConverter](https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-samples/nacos-spring-webmvc-sample/src/main/java/com/alibaba/nacos/samples/spring/listener/PojoNacosConfigListener.java) or [@NacosConfigurationProperties](https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample/Apple.java)
