### ISSUE TITLE
多文件部署

### ISSUE THREAD

**Issue by zhanglizhouchanghe** [nacos-group/nacos-spring-boot-project#57]
我有两个spring boot项目，用Nacos做配置中心，抽取了公共项目，但是 nacos.config.ext-config 整个属性不起作用，导致无法加载多个配置文
![QQ截图20190829164230](https://user-images.githubusercontent.com/54664124/63925093-0fb84200-ca7c-11e9-9270-9115f227c228.png)
![QQ截图20190829164214](https://user-images.githubusercontent.com/54664124/63925108-134bc900-ca7c-11e9-86a6-473ca4e5e1e8.png)
![QQ截图20190829164252](https://user-images.githubusercontent.com/54664124/63925116-16df5000-ca7c-11e9-8020-b9a943d662ec.png)

件。

**Comment by chuntaojun** [comment]
能描述下具体操作，以及问题吗？是配置无法拉取下来？

**Comment by zhanglizhouchanghe** [comment]
> 能描述下具体操作，以及问题吗？是配置无法拉取下来？

已经解决了，依然还是配置文件加载顺序问题

**Comment by chuntaojun** [comment]
> > 能描述下具体操作，以及问题吗？是配置无法拉取下来？
> 
> 已经解决了，依然还是配置文件加载顺序问题

是nacos的问题，还是说使用方式不对？

**Comment by zhanglizhouchanghe** [comment]
> > > 能描述下具体操作，以及问题吗？是配置无法拉取下来？
> > 
> > 
> > 已经解决了，依然还是配置文件加载顺序问题
> 
> 是nacos的问题，还是说使用方式不对？

![image](https://user-images.githubusercontent.com/54664124/63947767-1fe71600-caaa-11e9-966d-9480684f3dec.png)
![image](https://user-images.githubusercontent.com/54664124/63947792-2f665f00-caaa-11e9-8571-f5ed9dbeb71d.png)
一开始是shi使用public空间，导致无法初始化bean，多配置文件加载不懂也是不是这个问题，因为之前没有自定义命名空间是没法启动的。官方的sample提供了帮助，还是还有点坑，摸索老半天。

**Comment by chuntaojun** [comment]
解决了就好，如果对于sample有不足或者文档不够的地方，欢迎pr或提issue

**Comment by zhanglizhouchanghe** [comment]
> 解决了就好，如果对于sample有不足或者文档不够的地方，欢迎pr或提issue
ok
