### ISSUE TITLE
Support ConfigurationProperties

### ISSUE THREAD

**Issue by yanlinly** [nacos-group/nacos-spring-boot-project#7]
can‘t load config from nacos, when use configurationProperties.

![image](https://user-images.githubusercontent.com/17695352/50672239-d70db900-1011-11e9-9d16-313b069d321b.png)

![image](https://user-images.githubusercontent.com/17695352/50672244-decd5d80-1011-11e9-8acc-291bb411b500.png)

**Comment by fangjian0423** [comment]
I think `@ConfigurationProperties` can replace by `@NacosConfigurationProperties`.

All of them using `BeanPostProcessor` to complete their tasks. But we can not decide orders.

**Comment by chuntaojun** [comment]
already support it，wait for me to raise pr

**Comment by chuntaojun** [comment]
#31
