### ISSUE TITLE
nacos-config读取控制台配置的json数据

### ISSUE THREAD

**Issue by ciweigg2** [nacos-group/nacos-spring-boot-project#8]
springboot是否可以用注解读取json数据

**Comment by fangjian0423** [comment]
Of course you can read json data.

**Comment by ciweigg2** [comment]
How to read, no way to find, there are examples, annotations can read it?

**Comment by fangjian0423** [comment]
Sorry, do not see it clearly. It is not supported.

I create an issue in nacos-spring-project https://github.com/nacos-group/nacos-spring-project/issues/77

**Comment by chuntaojun** [comment]
already fix
