### ISSUE TITLE
nacos.config.group不起作用

### ISSUE THREAD

**Issue by peterzhu1688** [nacos-group/nacos-spring-boot-project#85]
环境：nacos-springboot-starter 0.2.3 , nacos 1.1.3。
描述：在application.properties中配置nacos.config.group=xxx(非默认的DEFAULT_GROUP）不起作用。打印日志显示还是从DEFAULT_GROUP中拉取数据
![image](https://user-images.githubusercontent.com/23010793/65040306-a47cd400-d986-11e9-952d-3b98d493bdb7.png)

另外，如何在java -jar xxx.jar命令行中指定group

**Comment by chuntaojun** [comment]
```java
public class NacosConfigApplicationInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    private final Logger logger = LoggerFactory.getLogger(NacosConfigApplicationInitializer.class);

    private ConfigurableEnvironment environment;

    private NacosConfigProperties nacosConfigProperties;

    private NacosConfigLoader nacosConfigLoader;

    @Override
    public void initialize(ConfigurableApplicationContext context) {
        CacheableEventPublishingNacosServiceFactory singleton = CacheableEventPublishingNacosServiceFactory.getSingleton();
        singleton.setApplicationContext(context);
        environment = context.getEnvironment();
        nacosConfigLoader = new NacosConfigLoader(environment);
        nacosConfigLoader.setNacosServiceFactory(singleton);
        if (!isEnable()) {
            logger.info("[Nacos Config Boot] : The preload configuration is not enabled");
        } else {
            logger.info("[Nacos Config Boot] : The preload configuration is enabled");
     这里 >  nacosConfigProperties = NacosConfigPropertiesUtils.buildNacosConfigProperties(environment);
            Properties globalProperties = buildGlobalNacosProperties();
            MutablePropertySources mutablePropertySources = environment.getPropertySources();
            mutablePropertySources.addLast(reqGlobalNacosConfig(globalProperties, nacosConfigProperties.getType()));
            for (NacosConfigProperties.Config config : nacosConfigProperties.getExtConfig()) {
                mutablePropertySources.addLast(reqSubNacosConfig(config, globalProperties, config.getType()));
            }
        }
    }
}
```

这一步运行完后，看下对象的属性是什么

**Comment by chuntaojun** [comment]
我试过了，没有出现你说的那种问题

**Comment by peterzhu1688** [comment]
没在电脑前，确实有这个问题……




| |
朱荣
|
|
邮箱：peterzhu1688@163.com
|

签名由 网易邮箱大师 定制

在2019年09月17日 20:47，liaochuntao 写道：

我试过了，没有出现你说的那种问题

**Comment by peterzhu1688** [comment]
你的版本是0.2.3吗




| |
朱荣
|
|
邮箱：peterzhu1688@163.com
|

签名由 网易邮箱大师 定制

在2019年09月17日 20:48，peterzhu1688 写道：
没在电脑前，确实有这个问题……




| |
朱荣
|
|
邮箱：peterzhu1688@163.com
|

签名由 网易邮箱大师 定制

在2019年09月17日 20:47，liaochuntao 写道：

我试过了，没有出现你说的那种问题

**Comment by chuntaojun** [comment]
> 你的版本是0.2.3吗 

恩

**Comment by peterzhu1688** [comment]
![image](https://user-images.githubusercontent.com/23010793/65095878-7e424d00-d9f5-11e9-83bd-66f5262d9b32.png)
![image](https://user-images.githubusercontent.com/23010793/65095890-8b5f3c00-d9f5-11e9-969f-7ab5fbcf2397.png)
![image](https://user-images.githubusercontent.com/23010793/65095903-9ca84880-d9f5-11e9-871a-6c532055ff9b.png)

我这么配置应该是没啥问题啊，为啥启动时还是从默认的DEFAULT_GROUP拉数据呢

**Comment by chuntaojun** [comment]
配置文件的设置不会作用到注解中去

**Comment by peterzhu1688** [comment]
那我同一套代码在部署时想通过配置文件指定不同的group怎么实现

**Comment by chuntaojun** [comment]
${group-id}，直接使用类似@Value的操作就可以了，nacos.config.group是只作用于配置文件中的，不会将值透传设置到注解中去
