### ISSUE TITLE
@EnableNacos  @NacosProperties can  read from the properties file?

### ISSUE THREAD

**Issue by coderDylan** [nacos-group/nacos-spring-boot-project#86]
```
@Configuration
@EnableNacos(
        globalProperties =
        @NacosProperties(serverAddr = "${nacos.server-addr}",
                enableRemoteSyncConfig = "true",
                maxRetry = "5",
                configRetryTime = "4000",
                configLongPollTimeout = "26000")
```

I see the samples project, find the "${nacos.server-addr}" is read from evn（JAVA system Property）, we can use like custom impl ServletContextListener（exec  System.setProperties('xx','yy'） or  config JVM startup parameter (-D)
but，Our company is not allowed to use environmental variables or modify the start.sh，so i want the Properties  'serverAddr、namespace' read from the properties file ,like nacos-spring boot-project

**Comment by chuntaojun** [comment]
I put the issue of mobile to nacos-spring-project
