### ISSUE TITLE
如果@ConditionalOnProperty在类上，该注解无法从配置中心读取到数据

### ISSUE THREAD

**Issue by charish00** [nacos-group/nacos-spring-boot-project#87]
NacosPropertySourcePostProcessor的优先级不够，能否参照PropertyResourceConfigurer调整为PriorityOrdered,getOrder返回Ordered.LOWEST_PRECEDENCE。
这样可能导致nacos启动读取不到nacos.config.server-addr，但是这个问题可以用@AutoConfigureAfter(PropertyPlaceholderAutoConfiguration.class)规避掉

**Comment by chuntaojun** [comment]
这个已经解决了，具体看wiki

**Comment by lvlonghu-dadi01** [comment]
> 这个已经解决了，具体看wiki

wiki连接可以放一下？

**Comment by liangxianjin** [comment]
> > 这个已经解决了，具体看wiki
> 
> wiki连接可以放一下？

https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.2-%E4%BB%A5%E5%8F%8A-0.1.2%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C
