### ISSUE TITLE
使用原生spring boot @Value注解时,无法实现自动更新配置文件

### ISSUE THREAD

**Issue by FelixLiuSheng** [nacos-group/nacos-spring-boot-project#88]
版本0.2.3,更新配置时,无法实现自动更新配置文件

**Comment by chuntaojun** [comment]
请用@NacosValue注解

**Comment by fallsea** [comment]
@chuntaojun z这种方式侵入性太强了，原生注解不考虑支持吗

**Comment by chuntaojun** [comment]
> @chuntaojun z这种方式侵入性太强了，原生注解不考虑支持吗

只能说尽量靠近cloud的表现

**Comment by fallsea** [comment]
@chuntaojun 我有使用过`Apollo`的配置中心，在spring boot中通过原生注解也可以支持，不知道他们是怎么实现的

**Comment by chuntaojun** [comment]
> @chuntaojun 我有使用过`Apollo`的配置中心，在spring boot中通过原生注解也可以支持，不知道他们是怎么实现的

已经实现了，等待新版本发布吧

**Comment by FelixLiuSheng** [comment]
什么时候发版本呢！期待着使用
