### ISSUE TITLE
spring-boot nacos-config load config after dubbo starter

### ISSUE THREAD

**Issue by lisp2c** [nacos-group/nacos-spring-boot-project#9]
spring-boot 2.1.6  dubbo的OverrideDubboConfigApplicationListener#onApplicationEvent 加载时，ConfigurableEnvironment  中还没有nacos中配置的一些基本dubbo配置，dubbo.registry.address，dubbo.protocol.name等

![image](https://user-images.githubusercontent.com/29775716/51371202-782d6100-1b34-11e9-98ea-447f77c38690.png)

**Comment by chuntaojun** [comment]
> spring-boot 2.1.6 dubbo的OverrideDubboConfigApplicationListener#onApplicationEvent 加载时，ConfigurableEnvironment 中还没有nacos中配置的一些基本dubbo配置，dubbo.registry.address，dubbo.protocol.name等
> 
> ![image](https://user-images.githubusercontent.com/29775716/51371202-782d6100-1b34-11e9-98ea-447f77c38690.png)

在解决了

**Comment by chuntaojun** [comment]
already fix in #31
