### ISSUE TITLE
SpringBoot中怎么读取Nacos中json格式的文件？

### ISSUE THREAD

**Issue by wangjie1911** [nacos-group/nacos-spring-boot-project#90]

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-project/wiki/Nacos-Spring-Project-0.3.1-%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C

**Comment by BlueBlackR9** [comment]
请问这种怎么获取，链接里没有说明
{
    "people":[{
        "name":"xxx",
        "age":"11"
    },{
        "name":"xxx",
        "age":"11"
    }]
}
