### ISSUE TITLE
是不是不支持spring bean 的request 作用域？

### ISSUE THREAD

**Issue by domnli** [nacos-group/nacos-spring-boot-project#95]
nacos-config-spring-boot-starter
是不是不支持spring bean 的request 作用域？
我在项目里面配置一个scope为request 的 spring bean，应用无法启动：
Scope 'request' is not active for the current thread

**Comment by chuntaojun** [comment]
这个非nacos问题吧？你把具体的代码发一下看下

**Comment by domnli** [comment]
使用的阿里云ACM
这是bean配置
![image](https://user-images.githubusercontent.com/3281318/69214780-cc64ff80-0ba2-11ea-86a9-06db2e0a0e84.png)
这是报错信息
![image](https://user-images.githubusercontent.com/3281318/69214831-f74f5380-0ba2-11ea-8201-f06849f95c6e.png)

**Comment by chuntaojun** [comment]
这确实是一个问题，周末会修复

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2280

**Comment by chuntaojun** [comment]
already fix, use nacos-spring-context 0.3.5
