### ISSUE TITLE
Nacos配置中心如何实现高可用

### ISSUE THREAD

**Issue by zhuyouzhufu** [nacos-group/nacos-spring-boot-project#96]
我在使用spring boot整合nacos时，注册中心可以高可用。但是配置中心如何高可用（官方文档没有找到具体的实现）?因为我的配置文件是放在nacos配置中心的，但是设置nacos.config.server-addr=127.0.0.1:8848在127.0.0.1宕机(故意停掉后)项目就无法运行。可否用逗号隔断127.0.0.1:8848,127.0.0.2:8848,127.0.0.3:8848。如果第一个不可用就依次读下一个IP的配置

**Comment by chuntaojun** [comment]
可以这样配置server-addr的

**Comment by zhuyouzhufu** [comment]
@chuntaojun 谢谢，可以了。不过server-addr 你们阿里有许多插件。例如注册中心和Sentinel是(nacos举例) nacos://127.0.0.1:8848?backup=127.0.0.2:8848。这个你们是不是要统一一下格式，相对比我觉得这个可能在格式上会造成别人的困惑。(我不是找茬，不要打我)。在这里也衷心的祝福nacos越来越好，感谢你们中间件团队的奉献。
